package com.reagan.wxpt.pojo.common;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * CommonFraction generated by hbm2java
 */

public class CommonFraction implements java.io.Serializable {

	private long uid;
	private int quantity;
	private Date lastTime;
	private int lastQuantity;

	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}


	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}


	public int getLastQuantity() {
		return this.lastQuantity;
	}

	public void setLastQuantity(int lastQuantity) {
		this.lastQuantity = lastQuantity;
	}

}
