package com.reagan.wxpt.pojo.common;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1



/**
 * CommonCounties generated by hbm2java
 */

public class CommonCounties implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4292814546567192759L;
	private long uid;
	private String tel;
	private String mobile;
	private String zipcode;
	private String address;

	
	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}


	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}


	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}


	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
