package com.reagan.wxpt.pojo.common;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.reagan.wxpt.pojo.business.BusinessDistribution;
import com.reagan.wxpt.pojo.business.BusinessOrder;
import com.reagan.wxpt.pojo.business.BusinessShopcar;


/**
 * CommonMembers generated by hbm2java
 */

public class CommonMembers implements java.io.Serializable {

	private Long uid;
	private String openid;
	private String nickname;
	private int sex;
	private String city;
	private String country;
	private String province;
	private String language;
	private String subscribeTime;
	private int status;
	private Set<BusinessShopcar> businessShopcars = new HashSet<BusinessShopcar>(
			0);
	private Set<BusinessOrder> businessOrders = new HashSet<BusinessOrder>(0);
	private CommonCounties commonCounties;
	private CommonFraction commonFraction;
	private Set<BusinessDistribution> businessDistributions = new HashSet<BusinessDistribution>(
			0);

	public CommonMembers() {
	}

	public CommonMembers(String openid, String nickname, int sex, String city,
			String country, String province, String language,
			String subscribeTime) {
		this.openid = openid;
		this.nickname = nickname;
		this.sex = sex;
		this.city = city;
		this.country = country;
		this.province = province;
		this.language = language;
		this.subscribeTime = subscribeTime;
	}

	public CommonMembers(String openid, String nickname, int sex, String city,
			String country, String province, String language,
			String subscribeTime, Set<BusinessShopcar> businessShopcars,
			Set<BusinessOrder> businessOrders, CommonCounties commonCounties,
			CommonFraction commonFraction,
			Set<BusinessDistribution> businessDistributions) {
		this.openid = openid;
		this.nickname = nickname;
		this.sex = sex;
		this.city = city;
		this.country = country;
		this.province = province;
		this.language = language;
		this.subscribeTime = subscribeTime;
		this.businessShopcars = businessShopcars;
		this.businessOrders = businessOrders;
		this.commonCounties = commonCounties;
		this.commonFraction = commonFraction;
		this.businessDistributions = businessDistributions;
	}


	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}


	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}


	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}


	public int getSex() {
		return this.sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}


	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}


	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}


	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}


	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}


	public String getSubscribeTime() {
		return this.subscribeTime;
	}

	public void setSubscribeTime(String subscribeTime) {
		this.subscribeTime = subscribeTime;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Set<BusinessShopcar> getBusinessShopcars() {
		return this.businessShopcars;
	}

	public void setBusinessShopcars(Set<BusinessShopcar> businessShopcars) {
		this.businessShopcars = businessShopcars;
	}


	public Set<BusinessOrder> getBusinessOrders() {
		return this.businessOrders;
	}

	public void setBusinessOrders(Set<BusinessOrder> businessOrders) {
		this.businessOrders = businessOrders;
	}


	public CommonCounties getCommonCounties() {
		return this.commonCounties;
	}

	public void setCommonCounties(CommonCounties commonCounties) {
		this.commonCounties = commonCounties;
	}


	public CommonFraction getCommonFraction() {
		return this.commonFraction;
	}

	public void setCommonFraction(CommonFraction commonFraction) {
		this.commonFraction = commonFraction;
	}


	public Set<BusinessDistribution> getBusinessDistributions() {
		return this.businessDistributions;
	}

	public void setBusinessDistributions(
			Set<BusinessDistribution> businessDistributions) {
		this.businessDistributions = businessDistributions;
	}

}
