package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;



/**
 * BusinessGoods generated by hbm2java
 */

public class BusinessGoods implements java.io.Serializable {

	private static final long serialVersionUID = -8232662800623624371L;
	private Integer goid;
	private Integer companyId;
	private Integer shopId;
	private int shid;
	private String name;
	private BigDecimal price;
	private String description;
	private int quantity;
	private int payQuantity;
	private int evaluate;
	private int payType;
	private int status;
	
	
	public Integer getGoid() {
		return this.goid;
	}

	public void setGoid(Integer goid) {
		this.goid = goid;
	}
	
	public int getShid() {
		return this.shid;
	}

	public void setShid(int shid) {
		this.shid = shid;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	
	public int getPayQuantity() {
		return this.payQuantity;
	}

	public void setPayQuantity(int payQuantity) {
		this.payQuantity = payQuantity;
	}

	
	public int getEvaluate() {
		return this.evaluate;
	}

	public void setEvaluate(int evaluate) {
		this.evaluate = evaluate;
	}

	
	public int getPayType() {
		return this.payType;
	}

	public void setPayType(int payType) {
		this.payType = payType;
	}

	
	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Integer getShopId() {
		return shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

}
