package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.reagan.wxpt.pojo.common.CommonMembers;


/**
 * BusinessDistribution generated by hbm2java
 */

public class BusinessDistribution implements java.io.Serializable {

	private int ordid;
	private BusinessOrder businessOrder;
	private CommonMembers commonMembers;
	private String cusName;
	private String zip;
	private String tel;
	private String mobile;
	private String address;
	private int deliverMode;
	private Date deliverDate;
	private int isPay;

	public BusinessDistribution() {
	}

	public BusinessDistribution(BusinessOrder businessOrder,
			CommonMembers commonMembers, String cusName, String zip,
			String tel, String mobile, String address, int deliverMode,
			Date deliverDate, int isPay) {
		this.businessOrder = businessOrder;
		this.commonMembers = commonMembers;
		this.cusName = cusName;
		this.zip = zip;
		this.tel = tel;
		this.mobile = mobile;
		this.address = address;
		this.deliverMode = deliverMode;
		this.deliverDate = deliverDate;
		this.isPay = isPay;
	}

	
	public int getOrdid() {
		return this.ordid;
	}

	public void setOrdid(int ordid) {
		this.ordid = ordid;
	}

	
	public BusinessOrder getBusinessOrder() {
		return this.businessOrder;
	}

	public void setBusinessOrder(BusinessOrder businessOrder) {
		this.businessOrder = businessOrder;
	}

	
	public CommonMembers getCommonMembers() {
		return this.commonMembers;
	}

	public void setCommonMembers(CommonMembers commonMembers) {
		this.commonMembers = commonMembers;
	}

	
	public String getCusName() {
		return this.cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}

	
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	
	public int getDeliverMode() {
		return this.deliverMode;
	}

	public void setDeliverMode(int deliverMode) {
		this.deliverMode = deliverMode;
	}

	
	public Date getDeliverDate() {
		return this.deliverDate;
	}

	public void setDeliverDate(Date deliverDate) {
		this.deliverDate = deliverDate;
	}

	
	public int getIsPay() {
		return this.isPay;
	}

	public void setIsPay(int isPay) {
		this.isPay = isPay;
	}

}
