package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;



/**
 * BusinessDistribution generated by hbm2java
 */

public class BusinessDistribution implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -58469378799266252L;
	private Integer ordid;
	private Integer orderId;
	private Integer uid;
	private String cusName;
	private String zip;
	private String tel;
	private String mobile;
	private String address;
	private int deliverMode;
	private Date deliverDate;
	private int isPay;

	
	public int getOrdid() {
		return this.ordid;
	}

	public void setOrdid(int ordid) {
		this.ordid = ordid;
	}

	public String getCusName() {
		return this.cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}
	
	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getUid() {
		return uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public void setOrdid(Integer ordid) {
		this.ordid = ordid;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	
	public int getDeliverMode() {
		return this.deliverMode;
	}

	public void setDeliverMode(int deliverMode) {
		this.deliverMode = deliverMode;
	}

	
	public Date getDeliverDate() {
		return this.deliverDate;
	}

	public void setDeliverDate(Date deliverDate) {
		this.deliverDate = deliverDate;
	}

	
	public int getIsPay() {
		return this.isPay;
	}

	public void setIsPay(int isPay) {
		this.isPay = isPay;
	}

}
