package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.reagan.wxpt.pojo.common.CommonMembers;


/**
 * BusinessShopcar generated by hbm2java
 */

public class BusinessShopcar implements java.io.Serializable {

	private Integer scid;
	private CommonMembers commonMembers;
	private BusinessGoods businessGoods;
	private String goodsName;
	private int quantity;
	private Date date;
	private BigDecimal goodsPrice;
	private BigDecimal amount;

	public BusinessShopcar() {
	}

	public BusinessShopcar(CommonMembers commonMembers,
			BusinessGoods businessGoods, String goodsName, int quantity,
			Date date, BigDecimal goodsPrice, BigDecimal amount) {
		this.commonMembers = commonMembers;
		this.businessGoods = businessGoods;
		this.goodsName = goodsName;
		this.quantity = quantity;
		this.date = date;
		this.goodsPrice = goodsPrice;
		this.amount = amount;
	}


	public Integer getScid() {
		return this.scid;
	}

	public void setScid(Integer scid) {
		this.scid = scid;
	}


	public CommonMembers getCommonMembers() {
		return this.commonMembers;
	}

	public void setCommonMembers(CommonMembers commonMembers) {
		this.commonMembers = commonMembers;
	}


	public BusinessGoods getBusinessGoods() {
		return this.businessGoods;
	}

	public void setBusinessGoods(BusinessGoods businessGoods) {
		this.businessGoods = businessGoods;
	}


	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}


	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public BigDecimal getGoodsPrice() {
		return this.goodsPrice;
	}

	public void setGoodsPrice(BigDecimal goodsPrice) {
		this.goodsPrice = goodsPrice;
	}


	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

}
