package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;


/**
 * BusinessOrderDetail generated by hbm2java
 */

public class BusinessOrderDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5813446874915462750L;
	private Integer ordid;
	private Integer companyId;
	private Integer orderId;
	private Integer shopId;
	private Integer goodsId;
	private BigDecimal goodsPrice;
	private BigDecimal disPrice;
	private int discount;
	private int goodsQuantity;

	public int getOrdid() {
		return this.ordid;
	}

	public void setOrdid(int ordid) {
		this.ordid = ordid;
	}

	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getShopId() {
		return shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public Integer getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public void setOrdid(Integer ordid) {
		this.ordid = ordid;
	}

	public BigDecimal getGoodsPrice() {
		return this.goodsPrice;
	}

	public void setGoodsPrice(BigDecimal goodsPrice) {
		this.goodsPrice = goodsPrice;
	}


	public BigDecimal getDisPrice() {
		return this.disPrice;
	}

	public void setDisPrice(BigDecimal disPrice) {
		this.disPrice = disPrice;
	}


	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}


	public int getGoodsQuantity() {
		return this.goodsQuantity;
	}

	public void setGoodsQuantity(int goodsQuantity) {
		this.goodsQuantity = goodsQuantity;
	}

}
