package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.reagan.core.annotation.Mapper;


/**
 * BusinessCompany generated by hbm2java
 */
@Mapper(tableName="BUSINESS_COMPANY")
public class BusinessCompany implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5107593585161440601L;
	@Mapper(column="COID", insert=false, updateWhere=true)
	private Integer coid;
	
	@Mapper(column="CATEGORY_ID", update=true)
	private Integer categoryId;
	
	@Mapper(column="NAME", update=true)
	private String name;
	
	@Mapper(column="LEVEL", update=true)
	private int level;
	/**
	 * 结算方式
	 */
	@Mapper(column="SETTLE_TYPE", update=true)
	private int settleType;
	
	/**
	 * 服务类型
	 */
	@Mapper(column="SERVICE_TYPE", update=true)
	private int serviceType;
	
	@Mapper(column="SCALE", update=true)
	private int scale;
	
	@Mapper(column="SALES_NAME", update=true)
	private String salesName;
	
	@Mapper(column="CREATE_DATE")
	private Date createDate;
	
	@Mapper(column="CREATE_NAME")
	private String createName;
	
	@Mapper(column="STATUS", update=true)
	private Integer status;

	public BusinessCompany() {
	}

	public BusinessCompany(int categoryId, String name,
			String district, int level, int settleType, int serviceType,
			int scale, String salesName, Date createDate, int status) {
		this.categoryId = categoryId;
		this.name = name;
		this.level = level;
		this.settleType = settleType;
		this.serviceType = serviceType;
		this.scale = scale;
		this.salesName = salesName;
		this.createDate = createDate;
		this.status = status;
	}

	

	
	public Integer getCoid() {
		return this.coid;
	}

	public void setCoid(Integer coid) {
		this.coid = coid;
	}

	public Integer getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	
	public int getSettleType() {
		return this.settleType;
	}

	public void setSettleType(int settleType) {
		this.settleType = settleType;
	}

	
	public int getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(int serviceType) {
		this.serviceType = serviceType;
	}

	
	public int getScale() {
		return this.scale;
	}

	public void setScale(int scale) {
		this.scale = scale;
	}

	
	public String getSalesName() {
		return this.salesName;
	}

	public void setSalesName(String salesName) {
		this.salesName = salesName;
	}

	
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
