package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.reagan.wxpt.pojo.system.SysCategory;
import com.reagan.wxpt.pojo.system.SysMenuGroup;
import com.reagan.wxpt.pojo.system.SysRegionCategory;


/**
 * BusinessGoods generated by hbm2java
 */

public class BusinessGoods implements java.io.Serializable {

	private Integer goid;
	private BusinessCompany businessCompany;
	private SysCategory sysCategory;
	private BusinessShop businessShop;
	private SysRegionCategory sysRegionCategory;
	private int shid;
	private String name;
	private BigDecimal price;
	private String description;
	private int quantity;
	private int payQuantity;
	private int evaluate;
	private int payType;
	private int status;
	private Set<SysMenuGroup> sysMenuGroups = new HashSet<SysMenuGroup>(0);
	private Set<BusinessOrderDetail> businessOrderDetails = new HashSet<BusinessOrderDetail>(
			0);
	private Set<BusinessShopcar> businessShopcars = new HashSet<BusinessShopcar>(
			0);

	public BusinessGoods() {
	}

	public BusinessGoods(BusinessCompany businessCompany,
			SysCategory sysCategory, BusinessShop businessShop,
			SysRegionCategory sysRegionCategory, int shid, String name,
			BigDecimal price, String description, int quantity,
			int payQuantity, int evaluate, int payType) {
		this.businessCompany = businessCompany;
		this.sysCategory = sysCategory;
		this.businessShop = businessShop;
		this.sysRegionCategory = sysRegionCategory;
		this.shid = shid;
		this.name = name;
		this.price = price;
		this.description = description;
		this.quantity = quantity;
		this.payQuantity = payQuantity;
		this.evaluate = evaluate;
		this.payType = payType;
	}

	public BusinessGoods(BusinessCompany businessCompany,
			SysCategory sysCategory, BusinessShop businessShop,
			SysRegionCategory sysRegionCategory, int shid, String name,
			BigDecimal price, String description, int quantity,
			int payQuantity, int evaluate, int payType,
			Set<SysMenuGroup> sysMenuGroups,
			Set<BusinessOrderDetail> businessOrderDetails,
			Set<BusinessShopcar> businessShopcars) {
		this.businessCompany = businessCompany;
		this.sysCategory = sysCategory;
		this.businessShop = businessShop;
		this.sysRegionCategory = sysRegionCategory;
		this.shid = shid;
		this.name = name;
		this.price = price;
		this.description = description;
		this.quantity = quantity;
		this.payQuantity = payQuantity;
		this.evaluate = evaluate;
		this.payType = payType;
		this.sysMenuGroups = sysMenuGroups;
		this.businessOrderDetails = businessOrderDetails;
		this.businessShopcars = businessShopcars;
	}

	
	public Integer getGoid() {
		return this.goid;
	}

	public void setGoid(Integer goid) {
		this.goid = goid;
	}

	
	public BusinessCompany getBusinessCompany() {
		return this.businessCompany;
	}

	public void setBusinessCompany(BusinessCompany businessCompany) {
		this.businessCompany = businessCompany;
	}

	
	public SysCategory getSysCategory() {
		return this.sysCategory;
	}

	public void setSysCategory(SysCategory sysCategory) {
		this.sysCategory = sysCategory;
	}

	
	public BusinessShop getBusinessShop() {
		return this.businessShop;
	}

	public void setBusinessShop(BusinessShop businessShop) {
		this.businessShop = businessShop;
	}

	
	public SysRegionCategory getSysRegionCategory() {
		return this.sysRegionCategory;
	}

	public void setSysRegionCategory(SysRegionCategory sysRegionCategory) {
		this.sysRegionCategory = sysRegionCategory;
	}

	
	public int getShid() {
		return this.shid;
	}

	public void setShid(int shid) {
		this.shid = shid;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	
	public int getPayQuantity() {
		return this.payQuantity;
	}

	public void setPayQuantity(int payQuantity) {
		this.payQuantity = payQuantity;
	}

	
	public int getEvaluate() {
		return this.evaluate;
	}

	public void setEvaluate(int evaluate) {
		this.evaluate = evaluate;
	}

	
	public int getPayType() {
		return this.payType;
	}

	public void setPayType(int payType) {
		this.payType = payType;
	}

	
	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Set<SysMenuGroup> getSysMenuGroups() {
		return this.sysMenuGroups;
	}

	public void setSysMenuGroups(Set<SysMenuGroup> sysMenuGroups) {
		this.sysMenuGroups = sysMenuGroups;
	}

	
	public Set<BusinessOrderDetail> getBusinessOrderDetails() {
		return this.businessOrderDetails;
	}

	public void setBusinessOrderDetails(
			Set<BusinessOrderDetail> businessOrderDetails) {
		this.businessOrderDetails = businessOrderDetails;
	}

	
	public Set<BusinessShopcar> getBusinessShopcars() {
		return this.businessShopcars;
	}

	public void setBusinessShopcars(Set<BusinessShopcar> businessShopcars) {
		this.businessShopcars = businessShopcars;
	}

}
