package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.reagan.wxpt.pojo.common.CommonMembers;


/**
 * BusinessOrder generated by hbm2java
 */

public class BusinessOrder implements java.io.Serializable {

	private Integer ordid;
	private BusinessTransaction businessTransaction;
	private CommonMembers commonMembers;
	private String ordNumber;
	private Date date;
	private int status;
	private int goodsQuantity;
	private Date orderDate;
	private Date disDate;
	private BigDecimal amount;
	private int payMode;
	private BusinessOrderDetail businessOrderDetail;
	private BusinessDistribution businessDistribution;

	public BusinessOrder() {
	}

	public BusinessOrder(BusinessTransaction businessTransaction,
			CommonMembers commonMembers, String ordNumber, Date date,
			int status, int goodsQuantity, Date orderDate, Date disDate,
			BigDecimal amount, int payMode) {
		this.businessTransaction = businessTransaction;
		this.commonMembers = commonMembers;
		this.ordNumber = ordNumber;
		this.date = date;
		this.status = status;
		this.goodsQuantity = goodsQuantity;
		this.orderDate = orderDate;
		this.disDate = disDate;
		this.amount = amount;
		this.payMode = payMode;
	}

	public BusinessOrder(BusinessTransaction businessTransaction,
			CommonMembers commonMembers, String ordNumber, Date date,
			int status, int goodsQuantity, Date orderDate, Date disDate,
			BigDecimal amount, int payMode,
			BusinessOrderDetail businessOrderDetail,
			BusinessDistribution businessDistribution) {
		this.businessTransaction = businessTransaction;
		this.commonMembers = commonMembers;
		this.ordNumber = ordNumber;
		this.date = date;
		this.status = status;
		this.goodsQuantity = goodsQuantity;
		this.orderDate = orderDate;
		this.disDate = disDate;
		this.amount = amount;
		this.payMode = payMode;
		this.businessOrderDetail = businessOrderDetail;
		this.businessDistribution = businessDistribution;
	}


	public Integer getOrdid() {
		return this.ordid;
	}

	public void setOrdid(Integer ordid) {
		this.ordid = ordid;
	}


	public BusinessTransaction getBusinessTransaction() {
		return this.businessTransaction;
	}

	public void setBusinessTransaction(BusinessTransaction businessTransaction) {
		this.businessTransaction = businessTransaction;
	}


	public CommonMembers getCommonMembers() {
		return this.commonMembers;
	}

	public void setCommonMembers(CommonMembers commonMembers) {
		this.commonMembers = commonMembers;
	}


	public String getOrdNumber() {
		return this.ordNumber;
	}

	public void setOrdNumber(String ordNumber) {
		this.ordNumber = ordNumber;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}


	public int getGoodsQuantity() {
		return this.goodsQuantity;
	}

	public void setGoodsQuantity(int goodsQuantity) {
		this.goodsQuantity = goodsQuantity;
	}


	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}


	public Date getDisDate() {
		return this.disDate;
	}

	public void setDisDate(Date disDate) {
		this.disDate = disDate;
	}


	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}


	public int getPayMode() {
		return this.payMode;
	}

	public void setPayMode(int payMode) {
		this.payMode = payMode;
	}


	public BusinessOrderDetail getBusinessOrderDetail() {
		return this.businessOrderDetail;
	}

	public void setBusinessOrderDetail(BusinessOrderDetail businessOrderDetail) {
		this.businessOrderDetail = businessOrderDetail;
	}


	public BusinessDistribution getBusinessDistribution() {
		return this.businessDistribution;
	}

	public void setBusinessDistribution(
			BusinessDistribution businessDistribution) {
		this.businessDistribution = businessDistribution;
	}

}
