package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;



/**
 * BusinessOrder generated by hbm2java
 */

public class BusinessOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1908846686506396089L;
	private Integer ordid;
	private Integer transactionId;
	private Integer uid;
	private String ordNumber;
	private Date date;
	private int status;
	private int goodsQuantity;
	private Date orderDate;
	private Date disDate;
	private BigDecimal amount;
	private int payMode;
	private Integer orderDetailId;
	private Integer distributionId;

	public Integer getOrdid() {
		return this.ordid;
	}

	public void setOrdid(Integer ordid) {
		this.ordid = ordid;
	}


	public String getOrdNumber() {
		return this.ordNumber;
	}

	public void setOrdNumber(String ordNumber) {
		this.ordNumber = ordNumber;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}


	public int getGoodsQuantity() {
		return this.goodsQuantity;
	}

	public void setGoodsQuantity(int goodsQuantity) {
		this.goodsQuantity = goodsQuantity;
	}


	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}


	public Date getDisDate() {
		return this.disDate;
	}

	public void setDisDate(Date disDate) {
		this.disDate = disDate;
	}


	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}


	public int getPayMode() {
		return this.payMode;
	}

	public void setPayMode(int payMode) {
		this.payMode = payMode;
	}

	public Integer getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	public Integer getUid() {
		return uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getOrderDetailId() {
		return orderDetailId;
	}

	public void setOrderDetailId(Integer orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	public Integer getDistributionId() {
		return distributionId;
	}

	public void setDistributionId(Integer distributionId) {
		this.distributionId = distributionId;
	}
	
}
