package com.reagan.wxpt.pojo.business;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * BusinessPush generated by hbm2java
 */

public class BusinessPush implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6221547079602303150L;
	private Integer puid;
	private Integer attachmentId;
	private Integer type;
	private Date date;
	private String content;
	private Integer mode;
	private Integer status;
	private String createname;

	public Integer getPuid() {
		return this.puid;
	}

	public void setPuid(Integer puid) {
		this.puid = puid;
	}


	public int getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(int attachmentId) {
		this.attachmentId = attachmentId;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}


	public int getMode() {
		return this.mode;
	}

	public void setMode(int mode) {
		this.mode = mode;
	}


	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}


	public String getCreatename() {
		return this.createname;
	}

	public void setCreatename(String createname) {
		this.createname = createname;
	}

}
