package com.reagan.wxpt.pojo.system;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.reagan.core.annotation.Mapper;


/**
 * SysAttachment generated by hbm2java
 */
@Mapper(tableName="SYS_ATTACHMENT")
public class SysAttachment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3913958906744635704L;
	@Mapper(column="ATID", insert=false, updateWhere=true)
	private Integer atid;
	
	@Mapper(column="COMPANY_ID")
	private Integer companyId;
	
	@Mapper(column="ADVERTISEMENT_ID")
	private Integer advertisementId;
	
	@Mapper(column="GOODS_ID")
	private Integer goodsId;
	
	@Mapper(column="FILENAME")
	private String filename;
	
	@Mapper(column="PATH")
	private String path;
	
	@Mapper(column="DATE")
	private Date date;
	
	@Mapper(column="MIMETYPE")
	private String mimetype;
	
	@Mapper(column="CREATENAME")
	private String createname;

	public Integer getAtid() {
		return this.atid;
	}

	public void setAtid(Integer atid) {
		this.atid = atid;
	}

	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Integer getAdvertisementId() {
		return this.advertisementId;
	}

	public void setAdvertisementId(Integer advertisementId) {
		this.advertisementId = advertisementId;
	}


	public Integer getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}


	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}


	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public String getMimetype() {
		return this.mimetype;
	}

	public void setMimetype(String mimetype) {
		this.mimetype = mimetype;
	}


	public String getCreatename() {
		return this.createname;
	}

	public void setCreatename(String createname) {
		this.createname = createname;
	}

}
