package com.reagan.wxpt.pojo.system;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1


/**
 * SysConfig generated by hbm2java
 */

public class SysConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3168200914970724586L;
	private String key;
	private String value;
	private String description;

	public SysConfig() {
	}

	public SysConfig(String key, String value, String description) {
		this.key = key;
		this.value = value;
		this.description = description;
	}


	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}


	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}


	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
