package com.reagan.wxpt.pojo.system;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.reagan.wxpt.pojo.business.BusinessCompany;
import com.reagan.wxpt.pojo.business.BusinessGoods;
import com.reagan.wxpt.pojo.business.BusinessShop;


/**
 * SysCategory generated by hbm2java
 */

public class SysCategory implements java.io.Serializable {

	private Integer cateid;
	private SysCategory sysCategory;
	private String name;
	private int type;
	private int sort;
	private String descrption;
	private Set<BusinessCompany> businessCompanies = new HashSet<BusinessCompany>(
			0);
	private Set<BusinessShop> businessShops = new HashSet<BusinessShop>(0);
	private Set<SysCategory> sysCategories = new HashSet<SysCategory>(0);
	private Set<BusinessGoods> businessGoodses = new HashSet<BusinessGoods>(0);

	public SysCategory() {
	}

	public SysCategory(SysCategory sysCategory, String name, int type,
			int sort, String descrption) {
		this.sysCategory = sysCategory;
		this.name = name;
		this.type = type;
		this.sort = sort;
		this.descrption = descrption;
	}

	public SysCategory(SysCategory sysCategory, String name, int type,
			int sort, String descrption,
			Set<BusinessCompany> businessCompanies,
			Set<BusinessShop> businessShops, Set<SysCategory> sysCategories,
			Set<BusinessGoods> businessGoodses) {
		this.sysCategory = sysCategory;
		this.name = name;
		this.type = type;
		this.sort = sort;
		this.descrption = descrption;
		this.businessCompanies = businessCompanies;
		this.businessShops = businessShops;
		this.sysCategories = sysCategories;
		this.businessGoodses = businessGoodses;
	}


	public Integer getCateid() {
		return this.cateid;
	}

	public void setCateid(Integer cateid) {
		this.cateid = cateid;
	}


	public SysCategory getSysCategory() {
		return this.sysCategory;
	}

	public void setSysCategory(SysCategory sysCategory) {
		this.sysCategory = sysCategory;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}


	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}


	public String getDescrption() {
		return this.descrption;
	}

	public void setDescrption(String descrption) {
		this.descrption = descrption;
	}


	public Set<BusinessCompany> getBusinessCompanies() {
		return this.businessCompanies;
	}

	public void setBusinessCompanies(Set<BusinessCompany> businessCompanies) {
		this.businessCompanies = businessCompanies;
	}


	public Set<BusinessShop> getBusinessShops() {
		return this.businessShops;
	}

	public void setBusinessShops(Set<BusinessShop> businessShops) {
		this.businessShops = businessShops;
	}


	public Set<SysCategory> getSysCategories() {
		return this.sysCategories;
	}

	public void setSysCategories(Set<SysCategory> sysCategories) {
		this.sysCategories = sysCategories;
	}


	public Set<BusinessGoods> getBusinessGoodses() {
		return this.businessGoodses;
	}

	public void setBusinessGoodses(Set<BusinessGoods> businessGoodses) {
		this.businessGoodses = businessGoodses;
	}

}
