package com.reagan.wxpt.pojo.system;

import com.reagan.core.annotation.Mapper;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1



/**
 * SysCategory generated by hbm2java
 */
@Mapper(tableName="SYS_CATEGORY")
public class SysCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3033611939647200733L;
	@Mapper(column="CATEID", insert=false, updateWhere=true)
	private Integer cateid;
	
	@Mapper(column="PARENT_ID", update=true)
	private Integer categoryId;
	
	@Mapper(column="NAME", update=true)
	private String name;
	
	@Mapper(column="SORT", update=true)
	private Integer sort;
	
	@Mapper(column="DESCRPTION", update=true)
	private String descrption;
	
	public Integer getCateid() {
		return this.cateid;
	}

	public void setCateid(Integer cateid) {
		this.cateid = cateid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}


	public String getDescrption() {
		return this.descrption;
	}

	public void setDescrption(String descrption) {
		this.descrption = descrption;
	}

	public Integer getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

}
