package com.reagan.wxpt.pojo.system;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1



/**
 * SysCategory generated by hbm2java
 */

public class SysCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3033611939647200733L;
	private Integer cateid;
	private Integer categoryId;
	private String name;
	private int type;
	private int sort;
	private String descrption;
	
	public Integer getCateid() {
		return this.cateid;
	}

	public void setCateid(Integer cateid) {
		this.cateid = cateid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}


	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}


	public String getDescrption() {
		return this.descrption;
	}

	public void setDescrption(String descrption) {
		this.descrption = descrption;
	}

	public Integer getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

}
