package com.reagan.wxpt.pojo.system;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1


/**
 * SysMenus generated by hbm2java
 */

public class SysMenus implements java.io.Serializable {

	private Integer menuid;
	private SysMenuGroup sysMenuGroup;
	private String name;
	private int type;
	private String event;

	public SysMenus() {
	}

	public SysMenus(SysMenuGroup sysMenuGroup, String name, int type,
			String event) {
		this.sysMenuGroup = sysMenuGroup;
		this.name = name;
		this.type = type;
		this.event = event;
	}


	public Integer getMenuid() {
		return this.menuid;
	}

	public void setMenuid(Integer menuid) {
		this.menuid = menuid;
	}


	public SysMenuGroup getSysMenuGroup() {
		return this.sysMenuGroup;
	}

	public void setSysMenuGroup(SysMenuGroup sysMenuGroup) {
		this.sysMenuGroup = sysMenuGroup;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}


	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

}
