package com.reagan.wxpt.pojo.system;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1



/**
 * SysMenuGroup generated by hbm2java
 */

public class SysMenuGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7627542531109923088L;
	private Integer mgid;
	private Integer companyId;
	private Integer commandId;
	private Integer shopId;
	private Integer goodsId;
	
	public Integer getMgid() {
		return this.mgid;
	}

	public void setMgid(Integer mgid) {
		this.mgid = mgid;
	}

	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Integer getCommandId() {
		return commandId;
	}

	public void setCommandId(Integer commandId) {
		this.commandId = commandId;
	}

	public Integer getShopId() {
		return shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public Integer getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}
	
}
