package com.reagan.wxpt.pojo.system;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1



/**
 * SysRegionCategory generated by hbm2java
 */

public class SysRegionCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4633109690670960406L;
	private Integer rcid;
	private Integer regionCategoryId;
	private String name;
	private int type;
	private int sort;
	private int lng;
	private int lat;
	
	public Integer getRcid() {
		return this.rcid;
	}

	public void setRcid(Integer rcid) {
		this.rcid = rcid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}


	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}


	public int getLng() {
		return this.lng;
	}

	public void setLng(int lng) {
		this.lng = lng;
	}


	public int getLat() {
		return this.lat;
	}

	public void setLat(int lat) {
		this.lat = lat;
	}

	public Integer getRegionCategoryId() {
		return regionCategoryId;
	}

	public void setRegionCategoryId(Integer regionCategoryId) {
		this.regionCategoryId = regionCategoryId;
	}

}
