package com.reagan.wxpt.pojo;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * BusinessAdvertisement generated by hbm2java
 */

public class BusinessAdvertisement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2891285980722106428L;
	private Integer adid;
	private BusinessCompany businessCompany;
	private Integer shopId;
	private Integer goodsId;
	private String title;
	private String content;
	private Date date;
	private String url;
	private int sort;

	public BusinessAdvertisement() {
	}

	public BusinessAdvertisement(BusinessCompany businessCompany, String title,
			String content, Date date, String url, int sort) {
		this.businessCompany = businessCompany;
		this.title = title;
		this.content = content;
		this.date = date;
		this.url = url;
		this.sort = sort;
	}

	public BusinessAdvertisement(BusinessCompany businessCompany,
			Integer shopId, Integer goodsId, String title, String content,
			Date date, String url, int sort) {
		this.businessCompany = businessCompany;
		this.shopId = shopId;
		this.goodsId = goodsId;
		this.title = title;
		this.content = content;
		this.date = date;
		this.url = url;
		this.sort = sort;
	}

	
	public Integer getAdid() {
		return this.adid;
	}

	public void setAdid(Integer adid) {
		this.adid = adid;
	}

	public BusinessCompany getBusinessCompany() {
		return this.businessCompany;
	}

	public void setBusinessCompany(BusinessCompany businessCompany) {
		this.businessCompany = businessCompany;
	}

	
	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	
	public Integer getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

}
