package com.reagan.wxpt.pojo;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * BusinessCompanyAction generated by hbm2java
 */

public class BusinessCompanyAction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -329529366811648077L;
	private Integer caid;
	private Integer compnayId;
	private Integer shopId;
	private Integer goodsId;
	private String content;
	private Date date;
	private String name;
	private int type;

	public BusinessCompanyAction() {
	}

	public BusinessCompanyAction(String content, Date date, String name,
			int type) {
		this.content = content;
		this.date = date;
		this.name = name;
		this.type = type;
	}

	public BusinessCompanyAction(Integer compnayId, Integer shopId,
			Integer goodsId, String content, Date date, String name, int type) {
		this.compnayId = compnayId;
		this.shopId = shopId;
		this.goodsId = goodsId;
		this.content = content;
		this.date = date;
		this.name = name;
		this.type = type;
	}


	public Integer getCaid() {
		return this.caid;
	}

	public void setCaid(Integer caid) {
		this.caid = caid;
	}

	public Integer getCompnayId() {
		return this.compnayId;
	}

	public void setCompnayId(Integer compnayId) {
		this.compnayId = compnayId;
	}

	
	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	
	public Integer getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
