package com.reagan.wxpt.pojo;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * BusinessPush generated by hbm2java
 */

public class BusinessPush implements java.io.Serializable {

	private Integer puid;
	private int attachmentId;
	private int type;
	private Date date;
	private String content;
	private int mode;
	private int status;
	private String createname;

	public BusinessPush() {
	}

	public BusinessPush(int attachmentId, int type, Date date, String content,
			int mode, int status, String createname) {
		this.attachmentId = attachmentId;
		this.type = type;
		this.date = date;
		this.content = content;
		this.mode = mode;
		this.status = status;
		this.createname = createname;
	}


	public Integer getPuid() {
		return this.puid;
	}

	public void setPuid(Integer puid) {
		this.puid = puid;
	}


	public int getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(int attachmentId) {
		this.attachmentId = attachmentId;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}


	public int getMode() {
		return this.mode;
	}

	public void setMode(int mode) {
		this.mode = mode;
	}


	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}


	public String getCreatename() {
		return this.createname;
	}

	public void setCreatename(String createname) {
		this.createname = createname;
	}

}
