package com.reagan.wxpt.pojo;

// Generated 2014-3-14 10:25:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * SysMenuGroup generated by hbm2java
 */

public class SysMenuGroup implements java.io.Serializable {

	private Integer mgid;
	private BusinessCompany businessCompany;
	private SysCommand sysCommand;
	private BusinessShop businessShop;
	private BusinessGoods businessGoods;
	private Set<SysMenus> sysMenuses = new HashSet<SysMenus>(0);

	public SysMenuGroup() {
	}

	public SysMenuGroup(BusinessCompany businessCompany) {
		this.businessCompany = businessCompany;
	}

	public SysMenuGroup(BusinessCompany businessCompany, SysCommand sysCommand,
			BusinessShop businessShop, BusinessGoods businessGoods,
			Set<SysMenus> sysMenuses) {
		this.businessCompany = businessCompany;
		this.sysCommand = sysCommand;
		this.businessShop = businessShop;
		this.businessGoods = businessGoods;
		this.sysMenuses = sysMenuses;
	}


	public Integer getMgid() {
		return this.mgid;
	}

	public void setMgid(Integer mgid) {
		this.mgid = mgid;
	}


	public BusinessCompany getBusinessCompany() {
		return this.businessCompany;
	}

	public void setBusinessCompany(BusinessCompany businessCompany) {
		this.businessCompany = businessCompany;
	}


	public SysCommand getSysCommand() {
		return this.sysCommand;
	}

	public void setSysCommand(SysCommand sysCommand) {
		this.sysCommand = sysCommand;
	}


	public BusinessShop getBusinessShop() {
		return this.businessShop;
	}

	public void setBusinessShop(BusinessShop businessShop) {
		this.businessShop = businessShop;
	}

	
	public BusinessGoods getBusinessGoods() {
		return this.businessGoods;
	}

	public void setBusinessGoods(BusinessGoods businessGoods) {
		this.businessGoods = businessGoods;
	}


	public Set<SysMenus> getSysMenuses() {
		return this.sysMenuses;
	}

	public void setSysMenuses(Set<SysMenus> sysMenuses) {
		this.sysMenuses = sysMenuses;
	}

}
